# Generated by Django 3.2 on 2021-04-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxim', models.CharField(max_length=100)),
                ('more_about_me_1', models.CharField(max_length=200)),
                ('more_about_me_2', models.CharField(blank=True, max_length=200, null=True)),
                ('headline_favorite', models.CharField(blank=True, max_length=200, null=True)),
                ('favorites', models.ManyToManyField(null=True, to='base.favorite')),
                ('songs', models.ManyToManyField(null=True, to='base.song')),
            ],
        ),
    ]
