# Generated by Django 3.2 on 2021-04-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_aboutme_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='image_author',
            field=models.ImageField(blank=True, default='IMG_4694.jpg', null=True, upload_to='images'),
        ),
    ]
