# Generated by Django 3.2 on 2021-04-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_aboutme_image_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(blank=True, default='x.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='image_author',
            field=models.ImageField(blank=True, default='x.png', null=True, upload_to='images'),
        ),
    ]
