# Generated by Django 3.2 on 2021-04-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210427_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='x.png', null=True, upload_to='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='image',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='images_slide',
            field=models.ManyToManyField(null=True, to='base.images'),
        ),
    ]
