# Generated by Django 3.2 on 2021-04-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210427_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='title',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
