# Generated by Django 3.2 on 2021-04-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_images_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.IntegerField(null=True),
        ),
    ]
