# Generated by Django 3.2 on 2021-05-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='image_author',
            field=models.ImageField(blank=True, default='/images/x.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, default='/images/x.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/images/x.png', null=True, upload_to='images'),
        ),
    ]
