# Generated by Django 3.2 on 2021-05-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20210507_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='userComment',
        ),
    ]
