# Generated by Django 3.2 on 2021-05-07 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_postcomment_usercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='userComment',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x000001593C75D548>', max_length=200),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.profile'),
        ),
    ]
