# Generated by Django 3.2 on 2021-05-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20210507_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='userComment',
        ),
    ]
