# Generated by Django 3.2 on 2021-05-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_postcomment_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='post_comment',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='post_comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
