# Generated by Django 3.2 on 2021-05-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20210508_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='twitter',
            new_name='Facebook',
        ),
    ]
