# Generated by Django 3.0.8 on 2021-05-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20210527_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='image_author',
            field=models.ImageField(default='/images/x.jpg', upload_to='author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='/images/x.jpg', upload_to='posts'),
        ),
    ]
